// app/layout.js (or wherever your RootLayout is)
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "../../components/navbar";
import Sidebar from "../../components/sidebar";

const spacemono = localFont({
  variable: "--font-mono",
  display: "swap",
  src: [
    {
      path: "./fonts/SpaceMono-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/SpaceMono-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata = {
  title: "Tungsten Satellite",
  description: "Generated by create next app",
};

async function fetchApodImage() {
  const apiKey =
    process.env.NASA_APOD_KEY ||
    process.env.NEXT_PUBLIC_NASA_APOD_KEY ||
    "DEMO_KEY";
  const endpoint = `https://api.nasa.gov/planetary/apod?api_key=${encodeURIComponent(
    apiKey
  )}&thumbs=true`;
  try {
    const res = await fetch(endpoint, {
      next: { revalidate: 86400 },
    });
    if (!res.ok) {
      console.warn(
        "APOD fetch failed:",
        res.status,
        res.statusText,
        "- consider configuring NASA_APOD_KEY for more reliable access."
      );
      return null;
    }
    const data = await res.json();
    if (data.media_type === "image") {
      return data.hdurl || data.url || null;
    }
    if (data.media_type === "video" && data.thumbnail_url) {
      return data.thumbnail_url;
    }
    return null;
  } catch (err) {
    console.warn(
      "APOD fetch error:",
      err,
      "- consider configuring NASA_APOD_KEY for more reliable access."
    );
    return null;
  }
}

export default async function RootLayout({ children }) {
  const apodImageUrl = await fetchApodImage();
  const bodyStyle =
    apodImageUrl
      ? {
          "--page-background-image": `linear-gradient(180deg, rgba(8,8,12,0.88) 0%, rgba(8,8,12,0.92) 35%, rgba(12,12,16,0.96) 100%), url("${apodImageUrl}")`,
        }
      : undefined;

  return (
    <html lang="en">
      <body
        className={`${spacemono.variable} bg-neutral-800 text-white font-mono flex flex-col min-h-screen`}
        style={bodyStyle}
      >
        <Navbar />

        {/* main row: sidebar + content; flex-1 makes this row fill remaining height */}
        <div className="flex flex-1 min-h-0 max-w-screen w-full overflow-hidden">
          <Sidebar />

          {/* content column — allow it to scroll if content is larger than available height */}
          <main className="flex flex-1 min-h-0 flex-col overflow-y-auto overflow-x-hidden bg-neutral-800 text-white">
            <div className="flex flex-1 flex-col">{children}</div>
            <div className="h-8 shrink-0 lg:h-12" aria-hidden="true" />
          </main>
        </div>
      </body>
    </html>
  );
}
