// app/layout.js (or wherever your RootLayout is)
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "../../components/navbar";
import Sidebar from "../../components/sidebar";

const spacemono = localFont({
  variable: "--font-mono",
  display: "swap",
  src: [
    {
      path: "./fonts/SpaceMono-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/SpaceMono-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata = {
  title: "Tungsten Satellite",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${spacemono.variable} bg-neutral-800 text-white font-mono flex flex-col min-h-screen`}
      >
        <Navbar />

        {/* main row: sidebar + content; flex-1 makes this row fill remaining height */}
        <div className="flex flex-1 min-h-0 max-w-screen w-full overflow-hidden">
          <Sidebar />

          {/* content column — allow it to scroll if content is larger than available height */}
          <main className="flex flex-1 min-h-0 flex-col overflow-y-auto overflow-x-hidden bg-neutral-800 text-white">
            <div className="flex flex-1 flex-col">{children}</div>
            <div className="h-8 shrink-0 lg:h-12" aria-hidden="true" />
          </main>
        </div>
      </body>
    </html>
  );
}
